In [1]:
import pandas as pd
import numpy as np

In [2]:
df_whisper_tiny = pd.read_csv('processed_evaluation/processed_Whisper_tiny_evaluation.csv', index_col=0)
df_cleaned_whisper_tiny = pd.read_csv('processed_evaluation/processed_Whisper_tiny_cleaned_evaluation.csv', index_col=0)
df_whisper_large = pd.read_csv('processed_evaluation/processed_Whisper_large_evaluation.csv', index_col=0)
df_cleaned_whisper_large = pd.read_csv('processed_evaluation/processed_Whisper_large_cleaned_evaluation.csv', index_col=0)
df_googlecloud = pd.read_csv('processed_evaluation/processed_GoogleCloud_evaluation.csv', index_col=0)
df_cleaned_googlecloud = pd.read_csv('processed_evaluation/processed_GoogleCloud_cleaned_evaluation.csv', index_col=0)
df_wav2vec = pd.read_csv('processed_evaluation/processed_Wav2vec_evaluation.csv', index_col=0)
df_cleaned_wav2vec = pd.read_csv('processed_evaluation/processed_Wav2vec_cleaned_evaluation.csv', index_col=0)
df_wenet = pd.read_csv('processed_evaluation/processed_WeNet_evaluation.csv', index_col=0)
df_cleaned_wenet = pd.read_csv('processed_evaluation/processed_WeNet_cleaned_evaluation.csv', index_col=0)
df_azure = pd.read_csv('processed_evaluation/processed_Azure_evaluation.csv', index_col=0)
df_cleaned_azure = pd.read_csv('processed_evaluation/processed_Azure_cleaned_evaluation.csv', index_col=0)

modelnames = ['Whisper_tiny', 'Whisper_large', 'GoogleCloud', 'Wav2vec', 'WeNet', 'Azure']
eval_metrics = ['WER', 'CER', 'BLEU', 'WordNet_first', 'WordNet_all', 'GloVe', 'BERT', 'Sent2Vec']
dfs = [df_whisper_tiny, df_whisper_large, df_googlecloud, df_wav2vec, df_wenet, df_azure]
dfs_cleaned = [df_cleaned_whisper_tiny, df_cleaned_whisper_large, df_cleaned_googlecloud, df_cleaned_wav2vec, df_cleaned_wenet, df_cleaned_azure]

In [3]:
dict_scores = {}
for df, df_cleaned, modelname in zip(dfs, dfs_cleaned, modelnames):
    dict_scores[modelname] = df[eval_metrics].describe()
    print(f'{modelname} scores')
    display(dict_scores[modelname])
    dict_scores[f'{modelname}_cleaned'] = df_cleaned[eval_metrics].describe()
    print(f'{modelname}_cleaned scores')
    display(dict_scores[f'{modelname}_cleaned'])

Whisper_tiny scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,36883.000000,36883.000000,3.688300e+04,36883.000000,36883.000000,36883.000000,36921.000000,36921.000000
mean,0.877443,0.746644,1.275585e-01,0.274702,0.235629,0.581566,0.757026,0.029192
std,1.321128,1.389842,2.429479e-01,0.241583,0.201288,0.426285,0.140234,0.026131
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.789156,0.132766,0.000000
25%,0.428571,0.321429,0.000000e+00,0.000000,0.000000,0.098133,0.653094,0.013123
50%,0.777778,0.545455,1.384293e-231,0.310816,0.281874,0.778596,0.773296,0.020213
75%,1.000000,0.928571,1.456685e-01,0.409890,0.346939,0.965945,0.876262,0.034733
max,112.000000,119.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,0.392577

Whisper_tiny_cleaned scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,36190.000000,36190.000000,3.619000e+04,36190.000000,36190.000000,36190.000000,36217.000000,36217.000000
mean,0.818286,0.610229,1.327042e-01,0.279245,0.239527,0.593538,0.760708,0.023427
std,1.207181,1.034948,2.482480e-01,0.241786,0.201621,0.423129,0.138635,0.017294
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.792815,0.132766,0.000000
25%,0.428571,0.300000,0.000000e+00,0.000000,0.000000,0.130018,0.660468,0.012532
50%,0.750000,0.500000,1.468884e-231,0.314286,0.284183,0.796057,0.776284,0.019131
75%,1.000000,0.833333,1.800026e-01,0.411464,0.348378,0.967715,0.878302,0.029877
max,111.000000,110.500000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,0.384278

Whisper_large scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,37210.000000,37210.000000,3.721000e+04,37210.000000,37210.000000,37210.000000,37247.000000,37247.000000
mean,0.390985,0.269152,3.342364e-01,0.411970,0.333076,0.785120,0.884498,0.021460
std,0.497369,0.362803,4.007899e-01,0.299386,0.247642,0.362024,0.101787,0.018093
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.709708,0.171050,0.000000
25%,0.000000,0.000000,1.821832e-231,0.266820,0.245206,0.767931,0.840316,0.010601
50%,0.227273,0.166667,6.868092e-78,0.402663,0.332647,0.988444,0.923171,0.015884
75%,0.600000,0.400000,7.366141e-01,0.576923,0.422222,1.000000,0.956937,0.025560
max,18.666667,11.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,0.357609

Whisper_large_cleaned scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,37124.000000,37124.000000,3.712400e+04,37124.000000,37124.000000,37124.000000,37158.000000,37158.000000
mean,0.373591,0.255282,3.425479e-01,0.412210,0.333109,0.792460,0.884049,0.019808
std,0.474129,0.319473,4.047384e-01,0.299627,0.247852,0.360291,0.102214,0.014335
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.709708,0.254236,0.000000
25%,0.000000,0.000000,1.821832e-231,0.269805,0.244999,0.805642,0.839630,0.010345
50%,0.211032,0.157895,7.380245e-78,0.402058,0.332445,0.989958,0.922540,0.015656
75%,0.545455,0.400000,7.506239e-01,0.576923,0.423001,1.000000,0.957667,0.024966
max,18.333333,10.125000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,0.259071

GoogleCloud scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,35893.000000,35893.000000,3.589300e+04,35893.000000,35893.000000,35893.000000,35888.000000,35888.000000
mean,0.316319,0.228332,3.342619e-01,0.457944,0.369484,0.839013,0.896251,0.019301
std,0.382334,0.281748,3.789695e-01,0.295579,0.244620,0.312422,0.093929,0.015395
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.752895,0.226360,0.000000
25%,0.000000,0.000000,1.054769e-154,0.323813,0.286244,0.883885,0.878093,0.009923
50%,0.235294,0.166667,1.221339e-77,0.422062,0.343982,0.984635,0.929652,0.015178
75%,0.500000,0.333333,6.582199e-01,0.590909,0.446291,1.000000,0.954075,0.023580
max,8.000000,11.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,0.278697

GoogleCloud_cleaned scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,35762.000000,35762.000000,3.576200e+04,35762.000000,35762.000000,35762.000000,35757.000000,35757.000000
mean,0.306645,0.225099,3.355083e-01,0.458727,0.369698,0.842383,0.895194,0.019371
std,0.365168,0.260760,3.794326e-01,0.296228,0.245080,0.310530,0.094467,0.015014
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.742988,0.209427,0.000000
25%,0.000000,0.000000,1.054769e-154,0.324184,0.286135,0.893729,0.875829,0.010021
50%,0.228571,0.166667,1.221339e-77,0.422615,0.343996,0.985185,0.928876,0.015246
75%,0.500000,0.333333,6.606329e-01,0.590909,0.448579,1.000000,0.954075,0.023953
max,7.000000,5.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,0.278698

Wav2vec scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,36634.000000,36634.000000,3.663400e+04,36634.000000,36634.000000,36634.000000,36659.000000,36659.000000
mean,0.510310,0.336952,2.308291e-01,0.396307,0.323888,0.753612,0.859257,0.019030
std,0.464291,0.309433,3.214727e-01,0.287062,0.235044,0.368020,0.102467,0.013814
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.777462,0.358102,0.000000
25%,0.200000,0.125000,1.531972e-231,0.250000,0.239944,0.673086,0.805248,0.010124
50%,0.428571,0.258065,2.904790e-78,0.383916,0.324122,0.959797,0.890987,0.015308
75%,0.714286,0.500000,4.797544e-01,0.555556,0.411446,0.993713,0.938768,0.023560
max,8.000000,5.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,0.153474

Wav2vec_cleaned scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,36634.000000,36634.000000,3.663400e+04,36634.000000,36634.000000,36634.000000,36659.000000,36659.000000
mean,0.510310,0.336948,2.308291e-01,0.396305,0.323888,0.753609,0.859257,0.019030
std,0.464291,0.309425,3.214727e-01,0.287062,0.235044,0.368023,0.102467,0.013814
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.777462,0.358102,0.000000
25%,0.200000,0.125000,1.531972e-231,0.250000,0.239944,0.673086,0.805248,0.010124
50%,0.428571,0.258065,2.904790e-78,0.383916,0.324122,0.959797,0.890987,0.015308
75%,0.714286,0.500000,4.797544e-01,0.555556,0.411446,0.993713,0.938768,0.023560
max,8.000000,5.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,0.153474

WeNet scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,37118.000000,37118.000000,3.711800e+04,37118.000000,37118.000000,37118.000000,37148.000000,37148.000000
mean,0.292748,0.195605,3.780691e-01,0.450661,0.361391,0.846742,0.905864,0.018112
std,0.408755,0.264452,4.109162e-01,0.300241,0.246909,0.313484,0.084264,0.013170
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.686760,0.303426,0.000000
25%,0.000000,0.000000,9.170599e-155,0.323764,0.283988,0.908585,0.884894,0.009522
50%,0.160000,0.105263,1.221339e-77,0.425000,0.343982,0.994801,0.936679,0.014219
75%,0.428571,0.272727,7.788008e-01,0.590909,0.445175,1.000000,0.961048,0.021885
max,11.000000,8.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000,0.159472

WeNet_cleaned scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,37118.000000,37118.000000,3.711800e+04,37118.000000,37118.000000,37118.000000,0.0,0.0
mean,0.293351,0.196239,3.775356e-01,0.450734,0.361459,0.845992,NaN,NaN
std,0.408684,0.264836,4.107569e-01,0.300268,0.246952,0.314078,NaN,NaN
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.686760,NaN,NaN
25%,0.000000,0.000000,9.047425e-155,0.323739,0.283926,0.907646,NaN,NaN
50%,0.161290,0.106061,1.221339e-77,0.425000,0.343982,0.994775,NaN,NaN
75%,0.428571,0.272727,7.788008e-01,0.590909,0.445208,1.000000,NaN,NaN
max,11.000000,8.000000,1.000000e+00,1.000000,1.000000,1.000000,NaN,NaN

Azure scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,36762.000000,36762.000000,3.676200e+04,36761.000000,36761.000000,36762.000000,0.0,0.0
mean,0.287272,0.218487,3.677032e-01,0.467990,0.372930,0.861961,NaN,NaN
std,0.409516,0.304939,4.055711e-01,0.307493,0.253603,0.291889,NaN,NaN
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.684578,NaN,NaN
25%,0.000000,0.000000,1.054769e-154,0.331823,0.288065,0.914724,NaN,NaN
50%,0.153846,0.105662,1.221339e-77,0.435823,0.350447,0.994435,NaN,NaN
75%,0.437500,0.333333,7.598357e-01,0.611111,0.455177,1.000000,NaN,NaN
max,11.000000,8.000000,1.000000e+00,1.000000,1.000000,1.000000,NaN,NaN

Azure_cleaned scores

,WER,CER,BLEU,WordNet_first,WordNet_all,GloVe,BERT,Sent2Vec
count,36701.000000,36701.000000,3.670100e+04,36700.000000,36700.000000,36701.000000,0.0,0.0
mean,0.282643,0.217280,3.681993e-01,0.468844,0.373631,0.863337,NaN,NaN
std,0.402811,0.294091,4.058650e-01,0.307538,0.253803,0.291779,NaN,NaN
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,-0.684578,NaN,NaN
25%,0.000000,0.000000,1.054769e-154,0.332330,0.288100,0.919303,NaN,NaN
50%,0.153846,0.111111,1.221339e-77,0.436604,0.350132,0.994540,NaN,NaN
75%,0.428571,0.333333,7.607697e-01,0.611111,0.455272,1.000000,NaN,NaN
max,11.000000,7.333333,1.000000e+00,1.000000,1.000000,1.000000,NaN,NaN

In [4]:
for key, value in dict_scores.items():
    value.to_csv(f'statistics/{key}_statistics.csv')